### PR TITLE
Add out-of-the-box support for Debian 10

### LINKED ISSUE #11: Support Debian 10 out-of-the-box
Hi, currently I have to set the library_path for getting it to work with Debian 10:

TidyFFI.library_path = Dir['/usr/lib/x86_64-linux-gnu/libtidy.so*'].first

Maybe it would be interesting to add support for Debian 10 out-of-the-box, since it's a very popular Linux distribution.

Currently this is the path tried by tidy_ffi:

https://github.com/libc/tidy_ffi/blob/master/lib/tidy_ffi/lib_tidy.rb#L8

```ruby
  LIB_NAME = 'tidy'.freeze
  PATHS = Array([LIB_NAME] + Dir['/{opt,usr}/{,local/}lib{,64}/libtidy{,-*}.{dylib,so*}']).freeze
```

Maybe we could try changing it to:
```ruby
  LIB_NAME = 'tidy'.freeze
  PATHS = Array([LIB_NAME] + Dir['/{opt,usr}/{,local/}lib{,64}/{,x86_64-linux-gnu/}libtidy{,-*}.{dylib,so*}']).freeze
```

I didn't submit a PR because I'm not sure there would be a better way to test for such paths.

Thanks for `tidy_ffi`!

### PR DESCRIPTION
**Pull request by rosenfeld**
fixes #11

### CODE REVIEW

**Review by simi — APPROVED** [review]
:information_source: build error doesn't seem related (it is related to rvm unable to find Ruby binaries).

**Comment by simi** [comment]
@libc @spk any chance to review this?

**Comment by libc** [comment]
@simi why can't we rely on `ffi` gem to find it normally?

**Comment by libc** [comment]
```
Step 4/4 : RUN ruby -rtidy_ffi -e "p TidyFFI::Tidy.new('a string').clean"
 ---> Running in 9524a400db28
"<!DOCTYPE html>\n<html>\n<head>\n<meta name=\"generator\" content=\n\"HTML Tidy for HTML5 for Linux version 5.6.0\">\n<title></title>\n</head>\n<body>\na string\n</body>\n</html>\n"
Removing intermediate container 9524a400db28
 ---> be39d4e20e7c
Successfully built be39d4e20e7c
➜  tidy cat Dockerfile
FROM ruby

RUN apt-get -y update && apt-get install -y libtidy-dev
RUN gem install tidy_ffi

RUN ruby -rtidy_ffi -e "p TidyFFI::Tidy.new('a string').clean"
```

Seems like installing `libtidy-dev` makes it work out of the box, but not the other package. I'm going to look into it

**Pull request closed without merging**
